### ISSUE TITLE
Automated Microsoft Azure ranges

### ISSUE THREAD

**Issue by Oink70** [femueller/cloud-ip-ranges#1]
I noticed you are (sparsely) updating your Azure json.

I see nothing about what backend you are using, except you use a bot to update this repo, so let me share this bash line, to download the Azure json from cli:
```bash
curl -O $(curl -L https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519 | grep -a "click here to download manually" | sed -n 's/.*href="\([^"]*\)" .*/\1/p')
```

**Comment by femueller** [comment]
Fixed since https://github.com/femueller/cloud-ip-ranges/commit/fe953a1e95926b74824c00ebffe0137808601a84.

The MS Azure part wasn't automated yet, since this required specifically parsing the HTML.
Before I've been only downloading plain files in my exporting script.

I also haven't prioritized publishing the exporting script. If there is an interest for it, I could do it.
